version: '2'
services:
  postgres:
    image: 'postgres:12-alpine'
    environment:
      POSTGRES_SERVICE_DB: 'test'
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
      PGDATA: 'tmp/pgdata'
    ports:
      - 5432:5432
