name: Feature Branch CI

on:
  push:
    branches-ignore: 
      ['master', 'release/*']

jobs:
  
  test:
    name: Unit Tests
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11.0.4
      - name: Gradle Check
        run: ./gradlew clean check
      
  sonar:
    name: Test - SonarCloud Scan
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@master
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
      
