name: Feature Branch

on:
  push:
    branches:
      - master
  pull_request:
    branches-ignore:
      - 'dependabot/**'
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - 'dependabot/**'


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up JDK 11
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 11

      - name: Tests
        run: ./gradlew clean check integrationTest

      - uses: actions/upload-artifact@v2.2.4
        with:
          name: reports
          path: build/reports
